export const CHANGE_GENRE = `CHANGE_GENRE`;

export const LOAD_FILMS_REQUEST = `LOAD_FILMS_REQUEST`;
export const LOAD_FILMS_SUCCESS = `LOAD_FILMS_SUCCESS`;
export const LOAD_FILMS_ERROR = `LOAD_FILMS_ERROR`;

export const AUTHORIZATION_REQUEST = `AUTHORIZATION_REQUEST`;
export const AUTHORIZATION_SUCCESS = `AUTHORIZATION_SUCCESS`;
export const AUTHORIZATION_ERROR = `AUTHORIZATION_ERROR`;

export const AUTHENTICATED_USER = `AUTHENTICATED_USER`;

export const CHANGE_FAVORITES_REQUEST = `CHANGE_FAVORITES_REQUEST`;
export const CHANGE_FAVORITES_SUCCESS = `CHANGE_FAVORITES_SUCCESS`;
export const CHANGE_FAVORITES_ERROR = `CHANGE_FAVORITES_ERROR`;

export const LOAD_PROMO_MOVIE_REQUEST = `LOAD_PROMO_MOVIE_REQUEST`;
export const LOAD_PROMO_MOVIE_SUCCESS = `LOAD_PROMO_MOVIE_SUCCESS`;
export const LOAD_PROMO_MOVIE_ERROR = `LOAD_PROMO_MOVIE_ERROR`;

export const LOAD_REVIEWS_REQUEST = `LOAD_REVIEWS_REQUEST`;
export const LOAD_REVIEWS_SUCCESS = `LOAD_REVIEWS_SUCCESS`;
export const LOAD_REVIEWS_ERROR = `LOAD_REVIEWS_ERROR`;
